### ISSUE TITLE
Error: `ModuleNotFoundError: No module named 'res_net_use_this'` in `test.py`

### ISSUE THREAD

**Issue by AshkanArabim** [geekfeiw/CSI-Net#4]
After following the guide and putting the dataset into a folder called `data`, I'm seeing an error when I run `test.py`. Here's the full error:
```
(model-venv) PS C:\Users\ashka\Desktop\summer 23\temple REU\wifi project\pretrained csi models\CSI-Net> python .\test.py
Traceback (most recent call last):
  File "C:\Users\ashka\Desktop\summer 23\temple REU\wifi project\pretrained csi models\CSI-Net\test.py", line 29, in <module>
    resnet = torch.load('weights/res18_Train100.0Test93.001.pkl')
  File "C:\Users\ashka\Desktop\summer 23\temple REU\wifi project\pretrained csi models\model-venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\ashka\Desktop\summer 23\temple REU\wifi project\pretrained csi models\model-venv\lib\site-packages\torch\serialization.py", line 1043, in _legacy_load
    result = unpickler.load()
  File "C:\Users\ashka\Desktop\summer 23\temple REU\wifi project\pretrained csi models\model-venv\lib\site-packages\torch\serialization.py", line 848, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'res_net_use_this'
```

**Comment by massimo1980** [comment]
you can use PYTHONPATH env variable as workaround:
`max@sauron:/opt/CSI-Net$ PYTHONPATH=./model/ python test.py`
but after i got this error:
`Traceback (most recent call last):
  File "test.py", line 41, in <module>
    predict_label = resnet(samplesV)
  File "/home/max/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/c/Users/Max/esp/CSI-Net/model/res_net_use_this.py", line 198, in forward
    out1 = self.humanid(out)
  File "/home/max/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/max/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 640, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
  File "/home/max/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AvgPool2d' object has no attribute 'divisor_override'`
anyone can help ?
